<?php

namespace AppBundle\Repository;

/**
 * OrderDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
