<?php
/**
 * Created by PhpStorm.
 * User: Felix
 * Date: 2017/3/3
 * Time: 下午10:01
 */

namespace AppBundle\Admin;


use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;

class CategoryAdmin extends AbstractAdmin
{
	protected function configureFormFields(FormMapper $form)
	{
		#parent::configureFormFields($form);
		$form->add('name', 'text');
	}

	protected function configureDatagridFilters(DatagridMapper $filter)
	{
		#parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
		$filter->add('name');
	}

	protected function configureListFields(ListMapper $list)
	{
		#parent::configureListFields($list); // TODO: Change the autogenerated stub
		$list->addIdentifier('name');
	}
}